"""
Write a python function to find whether the parity of a given number is odd.
assert find_Parity(12) == False
"""


def find_Parity(num):
    """
    :param num: int
    :return: bool
    """
    return num % 2 == 1


if __name__ == '__main__':
    print(find_Parity(12))
    print(find_Parity(13))
    print(find_Parity(14))
    print(find_Parity(15))
    print(find_Parity(16))
    print(find_Parity(17))
    print(find_Parity(18))
    print(find_Parity(19))
    print(find_Parity(20))
    print(find_Parity(21))
    print(find_Parity(22))
    print(find_Parity(23))
    print(find_Parity(24))
    print(find_Parity(25))
    print(find_Parity(26))
    print(find_Parity(27))
    print(find_Parity(28))
    print(find_Parity(29))
    print(find_Parity(30))
    print(find_Parity(31))
    print(find_Parity(32))
    print(find_Parity(33))
    print(find_Parity(34))
    print(find_Parity(35))
    print(find_Parity(36))
    print(find_Parity(37))
    print(find_Parity(38))
    print(find_Parity(39))
    print(find_Parity(40))
    print(find_Parity(41))
    print(find_Parity(42))
    print(find_Parity(43))
    print(find_Parity(44))
    print(find_Parity(45))
    print(find_Parity(46))
    print(find_Parity(47))
    print(find_Parity(48))
    print(find_Parity(49))
    print(find_Parity(50))
    print(find_Parity(51))
    print(find_Parity(52))
    print(find_Parity(53))
    print(find_Parity(54))
    print(find_Parity(55))
    print(find_Parity(56))
    print(find_Parity(57))
    print(find_Parity(58))
    print(find_Parity(59))
    print(find_Parity(60))
    print(find_Parity(61))
    print(find_Parity(62))
    print(find_Parity(63))
    print(find_Parity(64))
    print(find_Parity(65))
    print(find_Parity(66))
    print(find_Parity(67))
    print(find_Parity(68))
    print(find_Parity(69))
    print(find_Parity(70))
    print(find_Parity(71))
    print(find_Parity(72))
    print(find_Parity(73))
    print(find_Parity(74))
    print(find_Parity(75))
    print(find_Parity(76))
    print(find_Parity(77))
    print(find_Parity(78))
    print(find_Parity(79))
    print(find_Parity(80))
    print(find_Parity(81))
    print(find_Parity(82))
    print(find_Parity(83))
    print(find_Parity(84))
    print(find_Parity(85))
    print(find_Parity(86))
    print(find_Parity(8