"""
Write a function to calculate the sum of perrin numbers.
assert cal_sum(9) == 49
"""


def cal_sum(n):
    """
    :param n: int
    :return: int
    """
    if n == 1:
        return 1
    else:
        return n + cal_sum(n - 1)


if __name__ == '__main__':
    print(cal_sum(9))
    print(cal_sum(10))
    print(cal_sum(11))
    print(cal_sum(12))
    print(cal_sum(13))
    print(cal_sum(14))
    print(cal_sum(15))
    print(cal_sum(16))
    print(cal_sum(17))
    print(cal_sum(18))
    print(cal_sum(19))
    print(cal_sum(20))
    print(cal_sum(21))
    print(cal_sum(22))
    print(cal_sum(23))
    print(cal_sum(24))
    print(cal_sum(25))
    print(cal_sum(26))
    print(cal_sum(27))
    print(cal_sum(28))
    print(cal_sum(29))
    print(cal_sum(30))
    print(cal_sum(31))
    print(cal_sum(32))
    print(cal_sum(33))
    print(cal_sum(34))
    print(cal_sum(35))
    print(cal_sum(36))
    print(cal_sum(37))
    print(cal_sum(38))
    print(cal_sum(39))
    print(cal_sum(40))
    print(cal_sum(41))
    print(cal_sum(42))
    print(cal_sum(43))
    print(cal_sum(44))
    print(cal_sum(45))
    print(cal_sum(46))
    print(cal_sum(47))
    print(cal_sum(48))
    print(cal_sum(49))
    print(cal_sum(50))
    print(cal_sum(51))
    print(cal_sum(52))
    print(cal_sum(53))
    print(cal_sum(54))
    print(cal_sum(55))
    print(cal_sum(56))
    print(cal_sum(57))
    print(cal_sum(58))
    print(cal_sum(59))
    print(cal_sum(60))
    print(cal_sum(61))
    print(cal_sum(62))
    print(cal_sum(63))
    print(cal_sum(64))
    print(cal_sum(65))
    print(cal_sum(66))
    print(cal_sum(67))
    print(cal_sum(68))
    print(cal_sum(69))
    print(cal_sum(70))
    print(cal_sum(71))
    print(cal_sum(72))
    print(cal_sum(73))
    print(cal_sum(74))
    print(cal_sum(75))
    print(cal_sum(76))
    print(cal_sum(77))
    print(cal_sum(78))
    print(cal_sum(79))
    print(cal_sum(80))
    print(cal_sum(81))
    print(cal_sum(82))
    print(cal_sum(83))
    print(cal_sum(84))
    print(cal_sum(85))
    print(cal_sum(86))
    print(cal_sum(87))
    print(cal_sum(88))
    print(cal_sum(89