"""
Write a python function to find the difference between the sum of cubes of the first n natural numbers and the sum of the first n natural numbers.
assert difference(3) == 30
"""


def difference(n):
    """
    :param n: int
    :return: int
    """
    return sum(range(n)) ** 2 - sum(range(n))


if __name__ == '__main__':
    print(difference(3))
    print(difference(4))
    print(difference(5))
    print(difference(6))
    print(difference(7))
    print(difference(8))
    print(difference(9))
    print(difference(10))
    print(difference(11))
    print(difference(12))
    print(difference(13))
    print(difference(14))
    print(difference(15))
    print(difference(16))
    print(difference(17))
    print(difference(18))
    print(difference(19))
    print(difference(20))
    print(difference(21))
    print(difference(22))
    print(difference(23))
    print(difference(24))
    print(difference(25))
    print(difference(26))
    print(difference(27))
    print(difference(28))
    print(difference(29))
    print(difference(30))
    print(difference(31))
    print(difference(32))
    print(difference(33))
    print(difference(34))
    print(difference(35))
    print(difference(36))
    print(difference(37))
    print(difference(38))
    print(difference(39))
    print(difference(40))
    print(difference(41))
    print(difference(42))
    print(difference(43))
    print(difference(44))
    print(difference(45))
    print(difference(46))
    print(difference(47))
    print(difference(48))
    print(difference(49))
    print(difference(50))
    print(difference(51))
    print(difference(52))
    print(difference(53))
    print(difference(54))
    print(difference(55))
    print(difference(56))
    print(difference(57))
    print(difference(58))
    print(difference(59))
    print(difference(60))
    print(difference(61))
    print(difference(62))
    print(difference(63))
    print(difference(64))
    print(difference(65))
    print(difference(66))
    print(difference(67))
    print(difference(68))
    print(difference(69))
    print(difference(70))
    print(difference(71))
    print(difference(72))
    print(difference(73))
    print(difference(74))
    print(difference(75))
    print(difference(76))
    print(difference(77))
    print(difference(78))
    print(difference(79))
    print(difference(80))
    print(difference(81))
    print(difference(82))
    print(difference(83))
    print(difference(84))
    print(difference(85))
    print(difference(86))
    print(difference(87))
    print(difference(88))
    print(difference(89))
    print(difference(90))
    print(difference(91))
    print(difference(92))
    print(difference(93))
    print(difference(94))
    print(d