"""
Write a function to toggle the case of all characters in a string.
assert toggle_string("Python")==("pYTHON")
"""


def toggle_string(string):
    """
    :param string: string to toggle
    :return: string with toggled case
    """
    return ''.join([chr(97 + (ord(char) - 97) % 2) if char.isalpha() else char for char in string])


if __name__ == '__main__':
    print(toggle_string("Python"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print(toggle_string("Pyth0n"))
    print