"""
Write a function that matches a string that has an 'a' followed by anything, ending in 'b'.
assert text_starta_endb("aabbbb")
"""


def text_starta_endb(text):
    return text.startswith("a") and text.endswith("b")


print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_endb("aabbbb"))
print(text_starta_end