"""
Write a function to find the nth decagonal number.
assert is_num_decagonal(3) == 27
"""

def is_num_decagonal(n):
    return (10*n**2 - 10*n + 21) % 30 == 0

def nth_decagonal(n):
    if is_num_decagonal(n):
        return (10*n**2 - 10*n + 21) // 30
    else:
        return None

print(nth_decagonal(1))
print(nth_decagonal(2))
print(nth_decagonal(3))
print(nth_decagonal(4))
print(nth_decagonal(5))
print(nth_decagonal(6))
print(nth_decagonal(7))
print(nth_decagonal(8))
print(nth_decagonal(9))
print(nth_decagonal(10))
print(nth_decagonal(11))
print(nth_decagonal(12))
print(nth_decagonal(13))
print(nth_decagonal(14))
print(nth_decagonal(15))
print(nth_decagonal(16))
print(nth_decagonal(17))
print(nth_decagonal(18))
print(nth_decagonal(19))
print(nth_decagonal(20))
print(nth_decagonal(21))
print(nth_decagonal(22))
print(nth_decagonal(23))
print(nth_decagonal(24))
print(nth_decagonal(25))
print(nth_decagonal(26))
print(nth_decagonal(27))
print(nth_decagonal(28))
print(nth_decagonal(29))
print(nth_decagonal(30))
print(nth_decagonal(31))
print(nth_decagonal(32))
print(nth_decagonal(33))
print(nth_decagonal(34))
print(nth_decagonal(35))
print(nth_decagonal(36))
print(nth_decagonal(37))
print(nth_decagonal(38))
print(nth_decagonal(39))
print(nth_decagonal(40))
print(nth_decagonal(41))
print(nth_decagonal(42))
print(nth_decagonal(43))
print(nth_decagonal(44))
print(nth_decagonal(45))
print(nth_decagonal(46))
print(nth_decagonal(47))
print(nth_decagonal(48))
print(nth_decagonal(49))
print(nth_decagonal(50))
print(nth_decagonal(51))
print(nth_decagonal(52))
print(nth_decagonal(53))
print(nth_decagonal(54))
print(nth_decagonal(55))
print(nth_decagonal(56))
print(nth_decagonal(57))
print(nth_decagonal(58))
print(nth_decagonal(59))
print(nth_decagonal(60))
print(nth_decagonal(61))
print(nth_decagonal(62))
print(nth_decagonal(63))
print(nth_decagonal(64))
print(nth_decagonal(65))
print(nth_decagonal(66))
print(nth_decagonal(67))
print(nth_decagonal(68))
print(nth_decagonal(69))
print(nth_decagonal(70))
print(nth_decagonal(71))
print(nth_decagonal(72))
print(nth_decagonal(73))
print(nth_decagonal(74))
print(nth_decagonal(75))
print(nth_decag