"""
Write a function that checks whether a string contains the 'a' character followed by two or three 'b' characters.
assert text_match_two_three("ac")==(False)
"""

def text_match_two_three(text):
    if text.count("a") == 1 and text.count("b") == 2 or text.count("b") == 3:
        return True
    else:
        return False

assert text_match_two_three("ac")==(False)
assert text_match_two_three("abc")==(True)
assert text_match_two_three("abbc")==(True)
assert text_match_two_three("abbb")==(True)
assert text_match_two_three("abbbb")==(False)
assert text_match_two_three("b")==(False)
assert text_match_two_three("b")==(False)
assert text_match_two_three("bb")==(False)
assert text_match_two_three("bb")==(False)
assert text_match_two_three("bbb")==(False)
assert text_match_two_three("bbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")==(False)
assert text_match_two_three("bbbbb")