"""
Write a python function that takes in an integer n and finds the sum of the first n even natural numbers that are raised to the fifth power.
assert even_Power_Sum(2) == 1056
"""

def even_Power_Sum(n):
    sum = 0
    for i in range(2, n+1, 2):
        sum += i**5
    return sum

print(even_Power_Sum(2))
print(even_Power_Sum(3))
print(even_Power_Sum(4))
print(even_Power_Sum(5))
print(even_Power_Sum(6))
print(even_Power_Sum(7))
print(even_Power_Sum(8))
print(even_Power_Sum(9))
print(even_Power_Sum(10))
print(even_Power_Sum(11))
print(even_Power_Sum(12))
print(even_Power_Sum(13))
print(even_Power_Sum(14))
print(even_Power_Sum(15))
print(even_Power_Sum(16))
print(even_Power_Sum(17))
print(even_Power_Sum(18))
print(even_Power_Sum(19))
print(even_Power_Sum(20))
print(even_Power_Sum(21))
print(even_Power_Sum(22))
print(even_Power_Sum(23))
print(even_Power_Sum(24))
print(even_Power_Sum(25))
print(even_Power_Sum(26))
print(even_Power_Sum(27))
print(even_Power_Sum(28))
print(even_Power_Sum(29))
print(even_Power_Sum(30))
print(even_Power_Sum(31))
print(even_Power_Sum(32))
print(even_Power_Sum(33))
print(even_Power_Sum(34))
print(even_Power_Sum(35))
print(even_Power_Sum(36))
print(even_Power_Sum(37))
print(even_Power_Sum(38))
print(even_Power_Sum(39))
print(even_Power_Sum(40))
print(even_Power_Sum(41))
print(even_Power_Sum(42))
print(even_Power_Sum(43))
print(even_Power_Sum(44))
print(even_Power_Sum(45))
print(even_Power_Sum(46))
print(even_Power_Sum(47))
print(even_Power_Sum(48))
print(even_Power_Sum(49))
print(even_Power_Sum(50))
print(even_Power_Sum(51))
print(even_Power_Sum(52))
print(even_Power_Sum(53))
print(even_Power_Sum(54))
print(even_Power_Sum(55))
print(even_Power_Sum(56))
print(even_Power_Sum(57))
print(even_Power_Sum(58))
print(even_Power_Sum(59))
print(even_Power_Sum(60))
print(even_Power_Sum(61))
print(even_Power_Sum(62))
print(even_Power_Sum(63))
print(even_Power_Sum(64))
print(even_Power_Sum(65))
print(even_Power_Sum(66))
print(even_Power_Sum(67))
print(even_Power_Sum(68))
print(even_Power_Sum(69))
print(even_Power_Sum(70))
print(even_Power_Sum(71))
print(even_Power_Sum(72))
print(even_Power_Sum(73))
print(even_Power_Sum(74))
print(even_Power_Sum(75))
print(even_Power_Sum(76))
print(even_Power_Sum(77))
print(even_Power_Sum(78))
print(even_Power_Sum(79))
print(even_