"""
Write a function that checks whether a string contains the 'a' character followed by two or three 'b' characters.
assert text_match_two_three("ac")==(False)
"""

def text_match_two_three(text):
    return text.count("ab") in (2,3)

print(text_match_two_three("ac"))
print(text_match_two_three("ab"))
print(text_match_two_three("abb"))
print(text_match_two_three("abbb"))
print(text_match_two_three("abbbb"))
print(text_match_two_three("abbbbb"))
print(text_match_two_three("abbbbbbb"))
print(text_match_two_three("abbbbbbbb"))
print(text_match_two_three("abbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_two_three("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
print(text_match_