"""
Write a function to find the first adverb and their positions in a given sentence.
assert find_adverb_position("clearly!! we can see the sky")==(0, 7, 'clearly')
"""
import re

def find_adverb_position(sentence):
    """
    Find the first adverb and their positions in a given sentence.
    """
    adverbs = ['rarely', 'barely', 'seldom', 'never', 'often', 'sometimes', 'usually', 'always', 'just', 'soon', 'yesterday', 'tomorrow', 'today', 'here', 'there', 'everywhere', 'anywhere', 'somewhere', 'above', 'below', 'beneath', 'beside', 'behind', 'beside', 'between', 'beneath', 'beside', 'behind', 'before', 'below', 'beside', 'behind', 'beneath', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside', 'behind', 'beside',