"""
Write a python function to remove first and last occurrence of a given character from the string.
assert remove_Occ("hello","l") == "heo"
"""
def remove_Occ(string, char):
    """
    Function to remove first and last occurrence of a given character from the string.
    :param string: string to be modified
    :param char: character to be removed
    :return: string with first and last occurrence of given character removed
    """
    return string[::] [:string.index(char) if string.index(char) != -1 else 0] + string[::] [::-1].index(char) if string[-1] == char else string[:-1]

assert remove_Occ("hello","l") == "heo"
assert remove_Occ("python","p") == "ython"
assert remove_Occ("python","y") == "python"
assert remove_Occ("python","t") == "pyhon"
assert remove_Occ("python","h") == "pyon"
assert remove_Occ("python","o") == "py"
assert remove_Occ("python","n") == "py"
assert remove_Occ("python","s") == "py"
assert remove_Occ("python","d") == "py"
assert remove_Occ("python","a") == "py"
assert remove_Occ("python","e") == "py"
assert remove_Occ("python","i") == "py"
assert remove_Occ("python","g") == "py"
assert remove_Occ("python","r") == "py"
assert remove_Occ("python","m") == "py"
assert remove_Occ("python","l") == "py"
assert remove_Occ("python","k") == "py"
assert remove_Occ("python","j") == "py"
assert remove_Occ("python","v") == "py"
assert remove_Occ("python","b") == "py"
assert remove_Occ("python","c") == "py"
assert remove_Occ("python","x") == "py"
assert remove_Occ("python","z") == "py"
assert remove_Occ("python","q") == "py"
assert remove_Occ("python","w") == "py"
assert remove_Occ("python","s") == "py"
assert remove_Occ("python","d") == "py"
assert remove_Occ("python","f") == "py"
assert remove_Occ("python","g") == "py"
assert remove_Occ("python","r") == "py"
assert remove_Occ("python","t") == "py"
assert remove_Occ("python","h") == "py"
assert remove_Occ("python","e") == "py"
assert remove_Occ("python","o") == "py"
assert remove_Occ("python","n") == "py"
assert remove_Occ("python","m") == "py"
assert remove_Occ("python","l") == "py"
assert remove_Occ("python","k") == "py"
assert remove_Occ("python","j") == "py"
assert remove_Occ("python","v") == "py"
assert remove_Occ("python","b") == "py"
assert remove_Occ("python","c") == "py"
assert remove_Occ("python","x") == "py"
assert remove_Occ("python","z") == "py"
assert remove_Occ("python","q") == "py"
assert remove_Occ("python","w") == "py"
assert remove_Occ("python","s") == "py"
assert remove_Occ("python","d") == "py"
assert remove_Occ("python","f") == "py"
assert remove_Occ("python","g") == "py"
assert remove_Occ("python","r") == "py"
assert remove_Occ("python","t") == "py"
assert remove_Occ("python","h") == "py"
assert remove_Occ("python","e") == "py"
assert remove_Occ("python","o") == "py"
assert remove_Occ("python","n") == "py"
assert remove_Occ("python","m") == "py"