"""
Write a python function to remove first and last occurrence of a given character from the string.
assert remove_Occ("hello","l") == "heo"
"""
def remove_Occ(string, char):
    first = string.find(char)
    last = string.rfind(char)
    if first == -1 or last == -1:
        return string
    elif first == last:
        return string[:first] + string[first+1:]
    else:
        return string[:first] + string[first+1:last] + string[last+1:]

print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","l")) # Output: ""
print(remove_Occ("","")) # Output: ""
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","")) # Output: ""
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","")) # Output: ""
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","")) # Output: ""
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","")) # Output: ""
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","")) # Output: ""
print(remove_Occ("hello","h")) # Output: "ello"
print(remove_Occ("hello","l")) # Output: "heo"
print(remove_Occ("hello","o")) # Output: "hell"
print(remove_Occ("hello","z")) # Output: "hello"
print(remove_Occ("hello","e")) # Output: "llo"
print(remove_Occ("hello","")) # Output: "hello"
print(remove_Occ("","")) # Output: ""
print(remove_Occ