"""
Write a function to replace characters in a string.
assert replace_char("polygon",'y','l')==("pollgon")
"""


def replace_char(string, old_char, new_char):
    """
    Replace all occurrences of old_char in string with new_char.
    """
    return string.replace(old_char, new_char)


if __name__ == '__main__':
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'a'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))
    print(replace_char("polygon", 'y', 'l'))
    print(replace_char("polygon", 'o', 'l'))
    print(replace_char("polygon", 'g', 'l'))
    print(replace_char("polygon", 'n', 'l'))
    print(replace_char("polygon", 'p', 'l'))
    print(replace_char("polygon", 'l', 'l'))