"""
Write a function to toggle the case of all characters in a string.
assert toggle_string("Python")==("pYTHON")
"""


def toggle_string(string):
    """
    :param string: string
    :return: string
    """
    return string.swapcase()


if __name__ == '__main__':
    print(toggle_string("Python"))
    print(toggle_string("python"))
    print(toggle_string("PythOn"))
    print(toggle_string("pYTHON"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_string("PythOn"))
    print(toggle_