"""
Write a function to check if a dictionary is empty
assert my_dict({10})==False
"""


def my_dict(dict):
    if dict:
        return False
    else:
        return True


print(my_dict({10}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3: 4}))
print(my_dict({}))
print(my_dict({1: 2, 3