"""
Write a function to reverse words seperated by spaces in a given string.
assert reverse_words("python program")==("program python")
"""


def reverse_words(string):
    """
    :param string: string to be reversed
    :return: reversed string
    """
    return " ".join(string.split()[::-1])


if __name__ == '__main__':
    print(reverse_words("python program"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print(reverse_words("python program is fun"))
    print