"""
Write a python function to convert a given string to uppercase.
assert is_upper("person") =="PERSON"
"""


def is_upper(string):
    """
    :param string: string to convert to uppercase
    :return: string in uppercase
    """
    return string.upper()


if __name__ == '__main__':
    print(is_upper("person"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))
    print(is_upper("PERSON"))