"""
Write a function to find all words which are at least 4 characters long in a string.
assert set(find_char_long('Please move back to stream')) == set(['Please', 'move', 'back', 'stream'])
"""


def find_char_long(string):
    """
    :param string: string
    :return: set of words
    """
    words = string.split()
    return set(word for word in words if len(word) >= 4)


if __name__ == '__main__':
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))
    print(find_char_long('Please move back to stream'))