"""
Write a function to check whether the given string is starting with a vowel or not using regex.
assert check_str("annie")
"""

import re


def check_str(string):
    """
    Checks if the given string starts with a vowel or not.
    :param string: string to check
    :return: True if string starts with a vowel, False otherwise
    """
    return re.match(r"^[aeiouAEIOU].*", string)


if __name__ == '__main__':
    print(check_str("annie"))
    print(check_str("ann"))
    print(check_str("annie1"))
    print(check_str("ann1"))
    print(check_str("1annie"))
    print(check_str("1ann"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("1 "))
    print(check_str(" a"))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_str(" a "))
    print(check_