"""
Write a python function to check whether all the characters are same or not.
assert all_Characters_Same("python") == False
"""


def all_Characters_Same(string):
    return len(set(string)) == 1


if __name__ == '__main__':
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("python"))
    print(all_Characters_Same("