"""
Write a python function to find the sum of non-repeated elements in a given list.
assert find_sum([1,2,3,1,1,4,5,6]) == 21
"""


def find_sum(arr):
    """
    :param arr: list of integers
    :return: sum of non-repeated elements in the list
    """
    # Write your code here
    # return sum(set(arr))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))
    # return sum(list(set(arr)))