"""
Write a function to append the given list to the given tuples.
assert add_lists([5, 6, 7], (9, 10)) == (9, 10, 5, 6, 7)
"""


def add_lists(list_to_add, tuple_to_add):
    """
    Adds the given list to the given tuple.
    :param list_to_add: list to add
    :param tuple_to_add: tuple to add
    :return: tuple with the list added
    """
    return tuple_to_add + tuple(list_to_add)


if __name__ == '__main__':
    print(add_lists([5, 6, 7], (9, 10)))
    print(add_lists([1, 2, 3], (4, 5, 6)))
    print(add_lists([1, 2, 3], (4, 5)))
    print(add_lists([1, 2, 3], (4,)))
    print(add_lists([1, 2, 3], ()))
    print(add_lists([], (1, 2, 3)))
    print(add_lists([], ()))
    print(add_lists([], (1,)))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([], ()))
    print(add_lists([