"""
Write a function to convert a string to a list of strings split on the space character.
assert string_to_list("python programming")==['python','programming']
"""


def string_to_list(string):
    return string.split()


if __name__ == '__main__':
    print(string_to_list("python programming"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_list("python programming is fun"))
    print(string_to_