"""
Write a function to find the volume of a cube given its side length.
assert volume_cube(3)==27
"""


def volume_cube(side):
    """
    :param side: side of the cube
    :return: volume of the cube
    """
    return side ** 3


if __name__ == '__main__':
    print(volume_cube(3))
    print(volume_cube(4))
    print(volume_cube(5))
    print(volume_cube(6))
    print(volume_cube(7))
    print(volume_cube(8))
    print(volume_cube(9))
    print(volume_cube(10))
    print(volume_cube(11))
    print(volume_cube(12))
    print(volume_cube(13))
    print(volume_cube(14))
    print(volume_cube(15))
    print(volume_cube(16))
    print(volume_cube(17))
    print(volume_cube(18))
    print(volume_cube(19))
    print(volume_cube(20))
    print(volume_cube(21))
    print(volume_cube(22))
    print(volume_cube(23))
    print(volume_cube(24))
    print(volume_cube(25))
    print(volume_cube(26))
    print(volume_cube(27))
    print(volume_cube(28))
    print(volume_cube(29))
    print(volume_cube(30))
    print(volume_cube(31))
    print(volume_cube(32))
    print(volume_cube(33))
    print(volume_cube(34))
    print(volume_cube(35))
    print(volume_cube(36))
    print(volume_cube(37))
    print(volume_cube(38))
    print(volume_cube(39))
    print(volume_cube(40))
    print(volume_cube(41))
    print(volume_cube(42))
    print(volume_cube(43))
    print(volume_cube(44))
    print(volume_cube(45))
    print(volume_cube(46))
    print(volume_cube(47))
    print(volume_cube(48))
    print(volume_cube(49))
    print(volume_cube(50))
    print(volume_cube(51))
    print(volume_cube(52))
    print(volume_cube(53))
    print(volume_cube(54))
    print(volume_cube(55))
    print(volume_cube(56))
    print(volume_cube(57))
    print(volume_cube(58))
    print(volume_cube(59))
    print(volume_cube(60))
    print(volume_cube(61))
    print(volume_cube(62))
    print(volume_cube(63))
    print(volume_cube(64))
    print(volume_cube(65))
    print(volume_cube(66))
    print(volume_cube(67))
    print(volume_cube(68))
    print(volume_cube(69))
    print(volume_cube(70))
    print(volume_cube(71))
    print(volume_cube(72))
    print(volume_cube(73))
    print(volume_cube(74))
    print(volume_cube(75))
    print(volume_cube(76))
    print(volume_cube(77))
    print(volume_cube(78))
    print(volume_cube(79))
    print(volume_cube(80))
    print(volume_