"""
Write a function to remove lowercase substrings from a given string.
assert remove_lowercase("PYTHon")==('PYTH')
"""


def remove_lowercase(string):
    """
    :param string: string to remove lowercase substrings from
    :return: string with lowercase substrings removed
    """
    return ''.join(i for i in string if i.isupper())


if __name__ == '__main__':
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(