"""
Write a python function to find the area of the largest triangle that can be inscribed in a semicircle with a given radius.
assert triangle_area(-1) == None
"""


def triangle_area(radius):
    if radius < 0:
        return None
    return (radius ** 2) * (2 ** 0.5) / 2


print(triangle_area(1))
print(triangle_area(2))
print(triangle_area(3))
print(triangle_area(4))
print(triangle_area(5))
print(triangle_area(6))
print(triangle_area(7))
print(triangle_area(8))
print(triangle_area(9))
print(triangle_area(10))
print(triangle_area(11))
print(triangle_area(12))
print(triangle_area(13))
print(triangle_area(14))
print(triangle_area(15))
print(triangle_area(16))
print(triangle_area(17))
print(triangle_area(18))
print(triangle_area(19))
print(triangle_area(20))
print(triangle_area(21))
print(triangle_area(22))
print(triangle_area(23))
print(triangle_area(24))
print(triangle_area(25))
print(triangle_area(26))
print(triangle_area(27))
print(triangle_area(28))
print(triangle_area(29))
print(triangle_area(30))
print(triangle_area(31))
print(triangle_area(32))
print(triangle_area(33))
print(triangle_area(34))
print(triangle_area(35))
print(triangle_area(36))
print(triangle_area(37))
print(triangle_area(38))
print(triangle_area(39))
print(triangle_area(40))
print(triangle_area(41))
print(triangle_area(42))
print(triangle_area(43))
print(triangle_area(44))
print(triangle_area(45))
print(triangle_area(46))
print(triangle_area(47))
print(triangle_area(48))
print(triangle_area(49))
print(triangle_area(50))
print(triangle_area(51))
print(triangle_area(52))
print(triangle_area(53))
print(triangle_area(54))
print(triangle_area(55))
print(triangle_area(56))
print(triangle_area(57))
print(triangle_area(58))
print(triangle_area(59))
print(triangle_area(60))
print(triangle_area(61))
print(triangle_area(62))
print(triangle_area(63))
print(triangle_area(64))
print(triangle_area(65))
print(triangle_area(66))
print(triangle_area(67))
print(triangle_area(68))
print(triangle_area(69))
print(triangle_area(70))
print(triangle_area(71))
print(triangle_area(72))
print(triangle_area(73))
print(triangle_area(74))
print(triangle_area(75))
print(triangle_area(76))
print(triangle_area(77))
print(triangle_area(78))
print(triangle_area(79))
print(triangle_area(80))
print(triangle_area(81))
print(triangle_area(82))
print(triangle_area(83))
print(triangle_area(84))
print(triangle_area(85))
print(triangle_area(86))
print(triangle_area(87))
print(triangle_area(88))
print(triangle_area(89))
print(triangle_area(90))
print(triangle_area(91))
print(triangle_area(92))
print(triangle_area(93))
print(triangle_area(94))
print(triangle