"""
Write a function that takes in a string and character, replaces blank spaces in the string with the character, and returns the string.
assert replace_blank("hello people",'@')==("hello@people")
"""


def replace_blank(string, character):
    """
    Takes in a string and character, replaces blank spaces in the string with the character, and returns the string.
    """
    return string.replace(" ", character)


if __name__ == "__main__":
    print(replace_blank("hello people", '@'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '&'))
    print(replace_blank("hello people", '!'))
    print(replace_blank("hello people", '?'))
    print(replace_blank("hello people", '.'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people", '*'))
    print(replace_blank("hello people",