"""
Write a function to find the ascii value of a character.
assert ascii_value('A')==65
"""


def ascii_value(character):
    """
    :param character: a character
    :return: the ascii value of the character
    """
    return ord(character)


if __name__ == '__main__':
    print(ascii_value('A'))
    print(ascii_value('B'))
    print(ascii_value('C'))
    print(ascii_value('D'))
    print(ascii_value('E'))
    print(ascii_value('F'))
    print(ascii_value('G'))
    print(ascii_value('H'))
    print(ascii_value('I'))
    print(ascii_value('J'))
    print(ascii_value('K'))
    print(ascii_value('L'))
    print(ascii_value('M'))
    print(ascii_value('N'))
    print(ascii_value('O'))
    print(ascii_value('P'))
    print(ascii_value('Q'))
    print(ascii_value('R'))
    print(ascii_value('S'))
    print(ascii_value('T'))
    print(ascii_value('U'))
    print(ascii_value('V'))
    print(ascii_value('W'))
    print(ascii_value('X'))
    print(ascii_value('Y'))
    print(ascii_value('Z'))
    print(ascii_value('a'))
    print(ascii_value('b'))
    print(ascii_value('c'))
    print(ascii_value('d'))
    print(ascii_value('e'))
    print(ascii_value('f'))
    print(ascii_value('g'))
    print(ascii_value('h'))
    print(ascii_value('i'))
    print(ascii_value('j'))
    print(ascii_value('k'))
    print(ascii_value('l'))
    print(ascii_value('m'))
    print(ascii_value('n'))
    print(ascii_value('o'))
    print(ascii_value('p'))
    print(ascii_value('q'))
    print(ascii_value('r'))
    print(ascii_value('s'))
    print(ascii_value('t'))
    print(ascii_value('u'))
    print(ascii_value('v'))
    print(ascii_value('w'))
    print(ascii_value('x'))
    print(ascii_value('y'))
    print(ascii_value('z'))
    print(ascii_value('0'))
    print(ascii_value('1'))
    print(ascii_value('2'))
    print(ascii_value('3'))
    print(ascii_value('4'))
    print(ascii_value('5'))
    print(ascii_value('6'))
    print(ascii_value('7'))
    print(ascii_value('8'))
    print(ascii_value('9'))
    print(ascii_value('!'))
    print(ascii_value('@'))
    print(ascii_value('#'))
    print(ascii_value('$'))
    print(ascii_value('%'))
    print(ascii_value('^'))
    print(ascii_value('&'))
    print(ascii_value('*'))
    print(ascii_value('('))
    print(ascii_value(')'))
    print(ascii_value('-'))
    print(ascii_value('_'))
    print(ascii_value('+'))
    print(ascii_value('='))
    print(ascii_value('['))
    print(ascii_value(']'))
    print(ascii_value('{'))
    print(ascii_value('}'))
    print(ascii_value('|'))
    print(ascii_value('\\'))
    print(ascii_value(';'))
    print(ascii_value(':'))
    print(ascii_value('"'))