"""
Write a function to check whether the given string starts and ends with the same character or not.
assert check_char("abba") == "Valid"
"""


def check_char(string):
    if string[0] == string[-1]:
        return "Valid"
    else:
        return "Invalid"


if __name__ == "__main__":
    print(check_char("abba"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check_char("abbaa"))
    print(check