"""
Write a function to remove lowercase substrings from a given string.
assert remove_lowercase("PYTHon")==('PYTH')
"""


def remove_lowercase(string):
    """
    :param string: string to remove lowercase substrings from
    :return: string without lowercase substrings
    """
    return ''.join(c for c in string if c.isupper())


if __name__ == '__main__':
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lowercase("PYTHon"))
    print(remove_lower