"""
Write a function to toggle the case of all characters in a string.
assert toggle_string("Python")==("pYTHON")
"""


def toggle_string(string):
    """
    Toggle the case of all characters in a string.
    :param string:
    :return:
    """
    return string.swapcase()


if __name__ == '__main__':
    print(toggle_string("Python"))
    print(toggle_string("pYTHON"))
    print(toggle_string("PythOn"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(toggle_string("pYTHON"))
    print(