"""
Write a python function to split a string into characters.
assert split('python') == ['p','y','t','h','o','n']
"""


def split(string):
    return [char for char in string]


if __name__ == '__main__':
    print(split('python'))
    print(split('hello'))
    print(split(''))
    print(split(' '))
    print(split('  '))
    print(split('  hello  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(split('  hello  world  '))
    print(