"""
Write a python function to check whether the given two integers have opposite sign or not.
assert opposite_Signs(1,-2) == True
"""


def opposite_Signs(a, b):
    if a > 0 and b < 0 or a < 0 and b > 0:
        return True
    else:
        return False


print(opposite_Signs(1, -2))
print(opposite_Signs(1, 2))
print(opposite_Signs(1, 1))
print(opposite_Signs(1, 0))
print(opposite_Signs(0, 1))
print(opposite_Signs(0, 0))
print(opposite_Signs(0, -1))
print(opposite_Signs(-1, 0))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Signs(-1, 1))
print(opposite_Signs(-1, -1))
print(opposite_Signs(-1, -2))
print(opposite_Signs(-1, 2))
print(opposite_Sign