"""
Write a function to check if the given integer is a prime number.
assert prime_num(13)==True
"""


def prime_num(num):
    if num == 1:
        return False
    for i in range(2, num):
        if num % i == 0:
            return False
    return True


if __name__ == '__main__':
    print(prime_num(13))
    print(prime_num(14))
    print(prime_num(15))
    print(prime_num(16))
    print(prime_num(17))
    print(prime_num(18))
    print(prime_num(19))
    print(prime_num(20))
    print(prime_num(21))
    print(prime_num(22))
    print(prime_num(23))
    print(prime_num(24))
    print(prime_num(25))
    print(prime_num(26))
    print(prime_num(27))
    print(prime_num(28))
    print(prime_num(29))
    print(prime_num(30))
    print(prime_num(31))
    print(prime_num(32))
    print(prime_num(33))
    print(prime_num(34))
    print(prime_num(35))
    print(prime_num(36))
    print(prime_num(37))
    print(prime_num(38))
    print(prime_num(39))
    print(prime_num(40))
    print(prime_num(41))
    print(prime_num(42))
    print(prime_num(43))
    print(prime_num(44))
    print(prime_num(45))
    print(prime_num(46))
    print(prime_num(47))
    print(prime_num(48))
    print(prime_num(49))
    print(prime_num(50))
    print(prime_num(51))
    print(prime_num(52))
    print(prime_num(53))
    print(prime_num(54))
    print(prime_num(55))
    print(prime_num(56))
    print(prime_num(57))
    print(prime_num(58))
    print(prime_num(59))
    print(prime_num(60))
    print(prime_num(61))
    print(prime_num(62))
    print(prime_num(63))
    print(prime_num(64))
    print(prime_num(65))
    print(prime_num(66))
    print(prime_num(67))
    print(prime_num(68))
    print(prime_num(69))
    print(prime_num(70))
    print(prime_num(71))
    print(prime_num(72))
    print(prime_num(73))
    print(prime_num(74))
    print(prime_num(75))
    print(prime_num(76))
    print(prime_num(77))
    print(prime_num(78))
    print(prime_num(79))
    print(prime_num(80))
    print(prime_num(81))
    print(prime_num(82))
    print(prime_num(83))
    print(prime_num(84))
    print(prime_num(85))
    print(prime_num(86))
    print(prime_num(87))
    print(prime_num(88))
    print(prime_num(89))
    print(prime_num(90))
    print(prime_num(91))
    print(prime_num(92))
    print(prime_num(93))
    print(prime_num(94))
    print(prime_num