"""
Write a function to check whether the given string is starting with a vowel or not using regex.
assert check_str("annie")
"""

import re


def check_str(str):
    return re.match(r"^[aeiouAEIOU]", str)


if __name__ == "__main__":
    print(check_str("annie"))
    print(check_str("ann"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str(" "))
    print(check_str("Annie"))
    print(check_str("Ann"))
    print(check_str("A"))
    print(check_str("a"))
    print(check_str("A"))
    print(check_str("1"))
    print(check_str(""))
    print(check_str("