"""
Write a python function to check whether all the characters are same or not.
assert all_Characters_Same("python") == False
"""


def all_Characters_Same(string):
    return all(string[0] == char for char in string)


print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all_Characters_Same("python"))
print(all