"""
Write a function to toggle the case of all characters in a string.
assert toggle_string("Python")==("pYTHON")
"""
def toggle_string(string):
    return string.swapcase()

print(toggle_string("Python")) # Output: "pYTHON"

# Test cases
print(toggle_string("Hello World")) # Output: "hELLO wORLD"
print(toggle_string("Python")) # Output: "pYTHON"
print(toggle_string("")) # Output: ""
print(toggle_string("12345")) # Output: "12345"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "aBcDeFg"
print(toggle_string("aBcDeFg")) # Output: "