"""
Write a python function to split a string into characters.
assert split('python') == ['p','y','t','h','o','n']
"""
def split_string(string):
    return list(string)

# Test cases
print(split_string('python')) # Output: ['p', 'y', 't', 'h', 'o', 'n']
print(split_string('hello')) # Output: ['h', 'e', 'l', 'l', 'o']
print(split_string('world')) # Output: ['w', 'o', 'r', 'l', 'd']
print(split_string('programming')) # Output: ['p', 'r', 'o', 'g', 'r', 'a', 'm', 'm', 'i', 'n', 'g']
print(split_string('')) # Output: []
print(split_string('a')) # Output: ['a']
print(split_string('')) # Output: []

# Test cases for empty string
# print(split_string('')) # Output: []
# print(split_string('a')) # Output: ['a']
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(split_string('')) # Output: []
# print(