"""
Write a python function to find the index of smallest triangular number with n digits. https://www.geeksforgeeks.org/index-of-smallest-triangular-number-with-n-digits/
assert find_Index(2) == 4
"""
def find_Index(n):
    i = 1
    count = 0
    while True:
        if len(str(i*(i+1)//2)) == n:
            count += 1
        if count == n:
            return i
        i += 1

print(find_Index(2))
print(find_Index(3))
print(find_Index(4))
print(find_Index(5))
print(find_Index(6))
print(find_Index(7))
print(find_Index(8))
print(find_Index(9))
print(find_Index(10))
print(find_Index(11))
print(find_Index(12))
print(find_Index(13))
print(find_Index(14))
print(find_Index(15))
print(find_Index(16))
print(find_Index(17))
print(find_Index(18))
print(find_Index(19))
print(find_Index(20))
print(find_Index(21))
print(find_Index(22))
print(find_Index(23))
print(find_Index(24))
print(find_Index(25))
print(find_Index(26))
print(find_Index(27))
print(find_Index(28))
print(find_Index(29))
print(find_Index(30))
print(find_Index(31))
print(find_Index(32))
print(find_Index(33))
print(find_Index(34))
print(find_Index(35))
print(find_Index(36))
print(find_Index(37))
print(find_Index(38))
print(find_Index(39))
print(find_Index(40))
print(find_Index(41))
print(find_Index(42))
print(find_Index(43))
print(find_Index(44))
print(find_Index(45))
print(find_Index(46))
print(find_Index(47))
print(find_Index(48))
print(find_Index(49))
print(find_Index(50))
print(find_Index(51))
print(find_Index(52))
print(find_Index(53))
print(find_Index(54))
print(find_Index(55))
print(find_Index(56))
print(find_Index(57))
print(find_Index(58))
print(find_Index(59))
print(find_Index(60))
print(find_Index(61))
print(find_Index(62))
print(find_Index(63))
print(find_Index(64))
print(find_Index(65))
print(find_Index(66))
print(find_Index(67))
print(find_Index(68))
print(find_Index(69))
print(find_Index(70))
print(find_Index(71))
print(find_Index(72))
print(find_Index(73))
print(find_Index(74))
print(find_Index(75))
print(find_Index(76))
print(find_Index(77))
print(find_Index(78))
print(find_Index(79))
print(find_Index(80))
print(find_Index(81))
print(find_Index(82))
print(find_Index(83))
print(find_Index(84))
print(find_Index(85))
print(find_Index(86))
print(find_Index(87))
print(find_Index