"""
Write a python function to find nth bell number.
assert bell_Number(2) == 2
"""

def bell_Number(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    else:
        return bell_Number(n-1) + bell_Number(n-2) + bell_Number(n-3) + 1

print(bell_Number(2))
print(bell_Number(3))
print(bell_Number(4))
print(bell_Number(5))
print(bell_Number(6))
print(bell_Number(7))
print(bell_Number(8))
print(bell_Number(9))
print(bell_Number(10))
print(bell_Number(11))
print(bell_Number(12))
print(bell_Number(13))
print(bell_Number(14))
print(bell_Number(15))
print(bell_Number(16))
print(bell_Number(17))
print(bell_Number(18))
print(bell_Number(19))
print(bell_Number(20))
print(bell_Number(21))
print(bell_Number(22))
print(bell_Number(23))
print(bell_Number(24))
print(bell_Number(25))
print(bell_Number(26))
print(bell_Number(27))
print(bell_Number(28))
print(bell_Number(29))
print(bell_Number(30))
print(bell_Number(31))
print(bell_Number(32))
print(bell_Number(33))
print(bell_Number(34))
print(bell_Number(35))
print(bell_Number(36))
print(bell_Number(37))
print(bell_Number(38))
print(bell_Number(39))
print(bell_Number(40))
print(bell_Number(41))
print(bell_Number(42))
print(bell_Number(43))
print(bell_Number(44))
print(bell_Number(45))
print(bell_Number(46))
print(bell_Number(47))
print(bell_Number(48))
print(bell_Number(49))
print(bell_Number(50))
print(bell_Number(51))
print(bell_Number(52))
print(bell_Number(53))
print(bell_Number(54))
print(bell_Number(55))
print(bell_Number(56))
print(bell_Number(57))
print(bell_Number(58))
print(bell_Number(59))
print(bell_Number(60))
print(bell_Number(61))
print(bell_Number(62))
print(bell_Number(63))
print(bell_Number(64))
print(bell_Number(65))
print(bell_Number(66))
print(bell_Number(67))
print(bell_Number(68))
print(bell_Number(69))
print(bell_Number(70))
print(bell_Number(71))
print(bell_Number(72))
print(bell_Number(73))
print(bell_Number(74))
print(bell_Number(75))
print(bell_Number(76))
print(bell_Number(77))
print(bell_Number(78))
print(bell_Number(79))
print(bell_Number(80))
print(bell_Number(81))
print(bell_Number(82))
print(bell_Number(83))
print(bell_Number(84))
print(bell_Number(85))
print(bell_Number(86))
print(bell_Number(87))
print(bell_Number(88))
print(bell_Number(89))
print(bell_Number(90))
print(bell_Number(91))
print(bell_Number(92))
print(bell_Number(93))
print(bell_Number(94))
print