def fix_spaces(text):
    """
    Given a string text, replace all spaces in it with underscores, 
    and if a string has more than 2 consecutive spaces, 
    then replace all consecutive spaces with - 
    
    fix_spaces("Example") == "Example"
    fix_spaces("Example 1") == "Example_1"
    fix_spaces(" Example 2") == "_Example_2"
    fix_spaces(" Example   3") == "_Example-3"
    """
    # replace single spaces with underscores
    text = text.replace(" ", "_")
    # replace more than 2 consecutive spaces with -
    text = text.replace("  ", "-")
    text = text.replace("___", "-")
    text = text.replace("____", "-")
    text = text.replace("_____", "-")
    text = text.replace("______", "-")
    text = text.replace("_______", "-")
    text = text.replace("______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______", "-")
    text = text.replace("_______